CREATE SCHEMA ecm AUTHORIZATION postgres;
GRANT ALL ON SCHEMA ecm TO postgres;
CREATE ROLE ecm NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'ecm';
GRANT ALL ON SCHEMA ecm TO ecm;