version: '3.9'
services:
  postgres:
    container_name: ecm_postgres
    image: 'postgres:15.1-alpine'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecm
    volumes: 
      - ecm_postgres_data:/var/lib/postgresql/data
      - ./ecm_sql/src/main/resources/db/init_db.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - ecm_network

volumes:
  ecm_postgres_data:
    driver: local

networks:
  ecm_network:
    driver: bridge
